### ISSUE TITLE
clearpath_hardware_interface joints effort values NaN

### ISSUE THREAD

**Issue by adamanov** [clearpathrobotics/clearpath_robot#222]
Hello, 
I do have a mobile manipulator platform (jackal with open manipulator arm and gripper)
therefore i do use Moveit for manipulating the arm, 
whenever we do you use jackal with moveit, we getting **NaN** values on `joint_states` topic which coming hardware interface. (see bellow). And this results in error logs  like

> | Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "rh_p12_rn_r2" from authority "Authority undetectable" because of a nan value in the transform 

We fixed to issue by remapping `joint_states` topic on another topic i.e.` platform_joint_states` and fixing this **NaN** by setting them to zero and republishing back on `joint_states` topic. However, this is kinda a work around, therefore we would appreaciate if you could set `effort` to zero instead **NaN**

```
header:
  stamp:
    sec: 1748873654
    nanosec: 316744521
  frame_id: ''
name:
- joint2
- joint3
- joint1
- joint4
- joint5
- joint6
- gripper
- rear_left_wheel_joint
- front_left_wheel_joint
- front_right_wheel_joint
- rear_right_wheel_joint
position:
- -0.29898300766944885
- 1.0882954597473145
- -2.7746007442474365
- 0.0002882005355786532
- 1.5676285028457642
- 0.36698538064956665
- 0.6776757836341858
- -0.015088335610926151
- -0.015088335610926151
- 0.0484544113278389
- 0.0484544113278389
velocity:
- 0.0
- 0.0
- 0.0
- 0.0010471976129338145
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
effort:
- -885.010009765625
- -3090.81005859375
- -244.79000854492188
- 156.02000427246094
- 115.67000579833984
- 53.80000305175781
- 365.8399963378906
- .nan
- .nan
- .nan
- .nan
---
```
