### ISSUE TITLE
Phidget Spatial IMU as a supported sensor

### ISSUE THREAD

**Issue by fbottarel** [clearpathrobotics/clearpath_robot#42]
**Describe the the feature you would like**
My team recently obtained a Husky through the MyBotShop european distributor, and the robot is outfitted with a PhidgetSpatial 3/3/3 Basic IMU and a Hokuyo UST-10 LIDAR. While the UST-10 configuration works just by adding 

```yaml
lidar2d:
  - model: hokuyo_ust
    urdf_enabled: true
    launch_enabled: true
    parent: base_link
    xyz: [0.0, 0.0, 0.0]
    rpy: [0.0, 0.0, 0.0]
    ros_parameters:
      urg_node:
        laser_frame_id: lidar2d_0_laser
        ip_address: 192.168.131.20
        ip_port: 10940
        angle_min: -2.356
        angle_max: 2.356
```

to the `robot.yaml` configuration, we'd like to also have the PhidgetSpatial IMU supported as well. Will these sensors be supported in the roadmap?

**Other notes**
Since I am working on equipping our own Husky with this sensor, I am willing to contribute to the development and test the configurations.
